cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/cask-versions'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'mongodb'
brew 'node'
brew 'python'
brew 'tree'
brew 'yarn'
brew 'zsh'

cask '1password'
cask 'airmail-beta'
cask 'bettertouchtool'
cask 'boostnote'
cask 'docker'
cask 'fantastical'
cask 'flux'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'insomnia'
cask 'iterm2'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
