add_newline = false

[golang]
symbol = ""

[java]
disabled = true

[kotlin]
format = ""

[gcloud]
disabled = true
symbol = ""

[kubernetes]
disabled = true

[line_break]
disabled = true

[aws]
disabled = true

[dotnet]
disabled = true

[docker_context]
disabled = true

[git_branch]
symbol = "ᛘ "

[nodejs]
symbol = "node "